latency-wait: "{{cookiecutter.latency_wait}}"
jobscript: "lsf_jobscript.sh"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
restart-times: "{{cookiecutter.restart_times}}"
jobs: "{{cookiecutter.jobs}}"
executor: "cluster-generic"
cluster-generic-submit-cmd: "lsf_submit.py"
cluster-generic-status-cmd: "lsf_status.py"
cluster-generic-cancel-cmd: "lsf_cancel.py"
max-jobs-per-second: "{{cookiecutter.max_jobs_per_second}}"
max-status-checks-per-second: "{{cookiecutter.max_status_checks_per_second}}"